import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.scss';

import { Header } from '@/components/Header';
import { AppContextProvider } from '@/components/AppContext';

const notoSans = Noto_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Questionnaire App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={notoSans.className}>
        <AppContextProvider>
          <Header />
          <div className='wrapper'>{children}</div>
        </AppContextProvider>
      </body>
    </html>
  );
}
